name = "DS6015"
uuid = "bd91c45e-bfbb-4d27-8ea5-54ba9fffe5d4"
authors = ["José Bayoán Santiago Calderón <jbs3hp@virginia.edu>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
